version: '3.8'

services:
  test-faucet:
    container_name: zeitgeist-test-faucet
    build:
      context: .
      target: test-faucet
    image: zeitgeist-test-faucet
    restart: unless-stopped
    volumes:
      - ./test-config.toml:/app/test-config.toml:ro
      - ./test-faucet.db:/app/test-faucet.db
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=production

  main-faucet:
    container_name: zeitgeist-main-faucet
    build:
      context: .
      target: main-faucet
    image: zeitgeist-main-faucet
    restart: unless-stopped
    volumes:
      - ./main-config.toml:/app/main-config.toml:ro
      - ./main-faucet.db:/app/main-faucet.db
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=production